/* Generated By:JavaCC: Do not edit this line. SassParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SassParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 1;
  /** RegularExpression Id. */
  int MSET = 2;
  /** RegularExpression Id. */
  int NUMBER = 3;
  /** RegularExpression Id. */
  int LGTH = 4;
  /** RegularExpression Id. */
  int TEQS = 5;
  /** RegularExpression Id. */
  int TNES = 6;
  /** RegularExpression Id. */
  int TGTS = 7;
  /** RegularExpression Id. */
  int TGES = 8;
  /** RegularExpression Id. */
  int TLTS = 9;
  /** RegularExpression Id. */
  int TLES = 10;
  /** RegularExpression Id. */
  int TEQN = 11;
  /** RegularExpression Id. */
  int TNEN = 12;
  /** RegularExpression Id. */
  int TGTN = 13;
  /** RegularExpression Id. */
  int TGEN = 14;
  /** RegularExpression Id. */
  int TLTN = 15;
  /** RegularExpression Id. */
  int TLEN = 16;
  /** RegularExpression Id. */
  int TNUM = 17;
  /** RegularExpression Id. */
  int CAT = 18;
  /** RegularExpression Id. */
  int CHAR = 19;
  /** RegularExpression Id. */
  int ADD = 20;
  /** RegularExpression Id. */
  int SUB = 21;
  /** RegularExpression Id. */
  int DIV = 22;
  /** RegularExpression Id. */
  int MUL = 23;
  /** RegularExpression Id. */
  int MOVE = 24;
  /** RegularExpression Id. */
  int JUMP = 25;
  /** RegularExpression Id. */
  int LABEL = 26;
  /** RegularExpression Id. */
  int JSR = 27;
  /** RegularExpression Id. */
  int RET = 28;
  /** RegularExpression Id. */
  int EXIT = 29;
  /** RegularExpression Id. */
  int OUT = 30;
  /** RegularExpression Id. */
  int POINTER = 31;
  /** RegularExpression Id. */
  int ACC = 32;
  /** RegularExpression Id. */
  int PUSH = 33;
  /** RegularExpression Id. */
  int DATA = 34;
  /** RegularExpression Id. */
  int DATB = 35;
  /** RegularExpression Id. */
  int DATC = 36;
  /** RegularExpression Id. */
  int DATD = 37;
  /** RegularExpression Id. */
  int ADDR = 38;
  /** RegularExpression Id. */
  int MEM = 39;
  /** RegularExpression Id. */
  int IN = 40;
  /** RegularExpression Id. */
  int STRING = 41;
  /** RegularExpression Id. */
  int POP = 42;
  /** RegularExpression Id. */
  int TOP = 43;
  /** RegularExpression Id. */
  int RAND = 44;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<EOL>",
    "<MSET>",
    "<NUMBER>",
    "<LGTH>",
    "<TEQS>",
    "<TNES>",
    "<TGTS>",
    "<TGES>",
    "<TLTS>",
    "<TLES>",
    "<TEQN>",
    "<TNEN>",
    "<TGTN>",
    "<TGEN>",
    "<TLTN>",
    "<TLEN>",
    "<TNUM>",
    "<CAT>",
    "<CHAR>",
    "<ADD>",
    "<SUB>",
    "<DIV>",
    "<MUL>",
    "<MOVE>",
    "<JUMP>",
    "<LABEL>",
    "<JSR>",
    "<RET>",
    "<EXIT>",
    "<OUT>",
    "<POINTER>",
    "<ACC>",
    "<PUSH>",
    "<DATA>",
    "<DATB>",
    "<DATC>",
    "<DATD>",
    "<ADDR>",
    "<MEM>",
    "<IN>",
    "<STRING>",
    "<POP>",
    "<TOP>",
    "<RAND>",
  };

}
